Address user review
OpenLiberty/guide-microprofile-config-profile pull request #10
Opened 2023-02-08 20:24 UTC by shin19991207

Address https://github.com/OpenLiberty/draft-guide-microprofile-config-profile/issues/9

2023-02-08 21:12 UTC, gkwan-ibm requested changes
suggest:

```
...override the default configuration values from the [hotspot file=2]`system/server.xml` file...
```
to
```
...override the default configuration [hotspot=variables file=2]`variable` values from the `system` server configuration file...
```

and update system server.xml as
```
...
   <!-- tag::variables[]-->
    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>
    <variable name="default.username" defaultValue="admin"/>
    <variable name="default.password" defaultValue="adminpwd"/>
    <variable name="context.root" defaultValue="system"/>
   <!-- end::variables[]-->
...
```

2023-02-08 21:17 UTC, gkwan-ibm commented
update `src/main/resources/META-INF/microprofile-config.properties` to `qyery/src/main/resources/META-INF/microprofile-config.properties`

2023-02-09 14:35 UTC, mbuamuh approved these changes

2023-02-09 14:36 UTC, mbuamuh approved these changes

2023-02-09 17:10 UTC, gkwan-ibm approved these changes

2023-02-09 17:10 UTC, merged